### ISSUE TITLE
Login seems to fail silently

### ISSUE THREAD

**Issue by davidbanham** [plivo/plivo-web-sdk-example#5]
```javascript
Plivo.onReady = function() {
    var user = 'redacted@phone.plivo.com';
    var pass = 'redacted';

    Plivo.conn.login(user, pass);
    console.log('login called') // This fires as expected
};

Plivo.onLogin = function() {
    console.log('caught onlogin'); // This never fires
    var dest = "redacted";
    Plivo.conn.call(dest); // When this function is manually triggered, this surfaces the error "PlivoWebSDK:error : you need to be logged in before make a call "
};

Plivo.onLoginFailed = function(err) {
    console.log('login failed', err); // This also never fires
};

Plivo.init({debug: true});

```

I would normally dig into the code to figure out the issue and possibly submit a PR, but the SDK appears to be closed source.

**Comment by tobiashieb** [comment]
+1 

![bildschirmfoto 2015-06-27 um 09 19 46](https://cloud.githubusercontent.com/assets/3649698/8390952/ccc57d62-1cad-11e5-9b88-a3d5b5f756e4.png)

**Comment by davidbanham** [comment]
I've taken my business elsewhere.

**Comment by bevenky** [comment]
@tobiashieb Our team is looking to see if we can reproduce this. 

@davidbanham Sorry to hear that. Were you not able to get this to work even later?

**Comment by tobiashieb** [comment]
@bevenky Maybe you can try to login at your demo instance: https://s3.amazonaws.com/plivowebrtc/phone.html

In my case even here the login doesn't work by using my plivo credentials.

**Comment by tsudot** [comment]
@tobiashieb Could you send me your endpoint username to kunal [at] plivo [dot] com ? I can dig in more to figure out the real issue.

**Comment by quilam** [comment]
I can't login either. I thought i did something wrong but I checked my username and and password for my endpoint and everything is correct

**Comment by tsudot** [comment]
@quilam did you follow this guide to set up your webRTC phone? https://www.plivo.com/docs/getting-started/web-sdk/make-outgoing-calls/

The webRTC client will not work with your Plivo credentials. You need to use your Plivo __endpoint__ credentials

**Comment by davidbanham** [comment]
So have you fixed the SDK so that it executes the `onLoginFailed` function? This issue isn't a help request from someone that is unclear on which credentials to use. It's a (10 month old) report that your SDK completely ignores the registered failure notification mechanism and fails silently instead.

**Comment by tsudot** [comment]
`onLoginFailed` has already been added to the SDK.

**Comment by davidbanham** [comment]
I was about to ask "in which version?" when I realised the SDK is unversioned. Yep.

**Comment by SaurabhSharma45** [comment]
Does anyone solved this issue.
I am able to log in in https://s3.amazonaws.com/plivowebrtc/phone.html#
But not in my application.

**Comment by stefax** [comment]
Just in case somebody still has an issue with not being able to login and console log messages being "websocket connection established" but then "Login failed". 

The issue in my case was that when creating the plivo endpoint i used a username like "foo" and plivo silently made something like "foo63289372278812" out of it. I didn't notice that at first.
