### ISSUE TITLE
Is the phone example broken?

### ISSUE THREAD

**Issue by vaidik** [plivo/plivo-web-sdk-example#6]
The phone example seems to be showing "Call Failed:Busy" every single time even when the destination number is not busy. Is the example broken?

**Comment by khankuan** [comment]
+1

**Comment by yeojz** [comment]
+1

Seems like the example server is not in operation?

**Comment by tobiashieb** [comment]
+1 

![bildschirmfoto 2015-06-27 um 09 19 46](https://cloud.githubusercontent.com/assets/3649698/8390948/b5474a94-1cad-11e5-9204-b0283bb9acdd.png)

**Comment by tsudot** [comment]
@vaidik Are you hosting the examples yourself? Which example server are you using?

**Comment by sddsdei** [comment]
we are using http://s3.amazonaws.com/plivowebrtc/phone.html#

**Comment by tsudot** [comment]
@sddsdei Could you send me your endpoint username at kunal (at) plivo (dot) com

**Comment by sddsdei** [comment]
Hi Kunal,

Thanks for the quick reply

This is my endpoint username : smartdatatest150702065602

Sorry for not sending you mail.

**Comment by tsudot** [comment]
Looks like an incorrect application is setup on your endpoint. Could you link it to the direct dial app? More docs here - https://www.plivo.com/docs/getting-started/web-sdk/make-outgoing-calls/

**Comment by sddsdei** [comment]
Hi Kunal,

I am trying to record calls in plivo.

this is the response of answer_url that i am building.

<Response>
<Record action="https://hmzitjaisl.localtunnel.me/receiveRecordingDetails/" startOnDialAnswer="true" redirect="false"/>
<Dial callerId="14154847489">
<Number>918149524302</Number>
</Dial>
</Response>


NOTE: i am able to make/receive calls and talk.

**Comment by tsudot** [comment]
@sddsdei  Could you please raise a support ticket (support@plivo.com) This does not seem like a web SDK issue. Closing.

**Comment by sddsdei** [comment]
plivo support sucks, they really do. I don't get response for days.

Please help me with the conference call. I want to make call and after sometime need to call another number and join these two calls in conference.

Please please help.
I have tried Google as hard as i could. but there documentation is also very poor.

**Comment by crmeye** [comment]
+1

**Comment by shineptm** [comment]
@sddsdei Are you able to make a call from a browser to a phone number using Plivo Web SDK.
