### ISSUE TITLE
request: serve gzipped javascript on S3

### ISSUE THREAD

**Issue by jakswa** [plivo/plivo-web-sdk-example#7]
Maybe I'm missing something obvious, but I just thought I'd surface that currently the [S3 link for this sdk](https://s3.amazonaws.com/plivosdk/web/plivo.min.js) isn't serving up a gzipped version. The minified version is 200KB+, whereas the gzipped version would be 49KB.

See this link for details about serving compressed javascript on S3: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

You'll know gzip is being served if you see a `Content-Encoding: gzip` header in the S3 response (chrome accepts gzip, for example). That header will also appear in this output:
```
➜ wget -S --header="accept-encoding: gzip"  https://s3.amazonaws.com/plivosdk/web/plivo.min.js
--2015-09-30 23:10:48--  https://s3.amazonaws.com/plivosdk/web/plivo.min.js
Resolving s3.amazonaws.com... 54.231.18.48
Connecting to s3.amazonaws.com|54.231.18.48|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Thu, 01 Oct 2015 03:10:50 GMT
  Last-Modified: Sat, 20 Dec 2014 01:33:28 GMT
  ETag: "53170dd7458e55429645db52c90700ba"
  Accept-Ranges: bytes
  Content-Type: application/x-javascript
  Content-Length: 219970
  Server: AmazonS3
Length: 219970 (215K) [application/x-javascript]
Saving to: 'plivo.min.js'

plivo.min.js            100%[====================================>] 214.81K  1.15MB/s   in 0.2s

2015-09-30 23:10:49 (1.15 MB/s) - 'plivo.min.js' saved [219970/219970]
```

edit: I realize this isn't the SDK repo, but this is the closest I could find. Feel free to direct me to the appropriate repo for this issue.

**Comment by cachrisman** [comment]
thanks for raising this issue. If you want to use a gzip version you can link to https://s3.amazonaws.com/plivosdk/web/plivo.min.js.gz
