### ISSUE TITLE
PlivoWebSDK:failed to create UA

### ISSUE THREAD

**Issue by anupsaund** [plivo/plivo-web-sdk-example#9]
I cloned this repository and tried the phone.html example.

Firstly - the login wouldn't accept my username, but I worked around that by entering my email address.

After that I had a login page that did nothing? So I checked the console and saw PlivoWebSDK:failed to create UA.

I tried this on a Windows 10 computer using Google Chrome.
Also tested on a Mac using Google Chrome.

I also tried the hosted version of it too - which gave me the same result.

![screen shot 2016-06-10 at 11 06 49](https://cloud.githubusercontent.com/assets/6728822/15961287/db498606-2efb-11e6-9537-6df292a00aa3.png)

<img width="1122" alt="screen shot 2016-06-10 at 11 05 49" src="https://cloud.githubusercontent.com/assets/6728822/15961290/e1facc3a-2efb-11e6-8d7b-c84381edfea7.png">

**Comment by cachrisman** [comment]
Did you create a Plivo Endpoint and use that username and password to login? You can't use your Plivo account credentials to log into this demo. You can create a Plivo Endpoint here: https://manage.plivo.com/endpoint/create/

**Comment by SaurabhSharma45** [comment]
PlivoWebSDK:Plivo SDK initialization
plivo.min.js:5 PlivoWebSDK:- User Agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
plivo.min.js:5 PlivoWebSDK:- Browser : Chrome  53
plivo.min.js:5 PlivoWebSDK:- OS : Mac
dialPadDirective.js:108 onReady...
dialPadDirective.js:91 get media permission
plivo.min.js:5 PlivoWebSDK | 17:56:59.539 | websocket connection established
plivo.min.js:5 PlivoWebSDK:Login failed
